server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hilizhixuan/microservicecloud-config.git #GitHub上面config仓库的位置